# **Questions 1 - 10**   **(Easy)**

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Dataset
data = {
'order_id': [1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,
1011,1012,1013,1014,1015,1016,1017,1018,1019,1020],
'customer_name':['Ali','Sara','John','Mia','Ahmed','Sara','John','Ali',
'Zara','Omar','Mia','Ahmed','Sara','John','Ali','Zara',
'Omar','Ahmed','Mia','Ali'],
'city': ['Lahore','Karachi','Islamabad','Lahore','Karachi',
'Karachi','Islamabad','Lahore','Karachi','Islamabad',
'Lahore','Karachi','Karachi','Islamabad','Lahore',
'Karachi','Islamabad','Karachi','Lahore','Lahore'],
'category': ['Electronics','Clothing','Books','Electronics','Clothing',
'Books','Electronics','Clothing','Books','Electronics',
'Clothing','Books','Electronics','Clothing','Electronics',
'Books','Clothing','Electronics','Books','Clothing'],
'product': ['Laptop','T-Shirt','Python Book','Headphones','Jeans',
'Novel','Charger','Hoodie','Notebook','Tablet',
'Dress','Cook Book','Smartwatch','Jacket','Mouse',
'Textbook','Scarf','Earbuds','Dictionary','Gloves'],
'quantity': [1, 3, 2, 1, 2, 1, 4, 2, 5, 1,
2, 3, 1, 2, 3, 2, 4, 1, 2, 3],
'price': [75000, 1200, 1800, 4500, 2500,
800, 600, 2200, 300, 45000,
1500, 900, 12000,3500, 1100,
1200, 800, 3200, 700, 1400],
'discount_pct': [10, 0, 5, 15, 0, 0, 20, 10, 5, 5,
0, 10, 15, 0, 10, 0, 5, 20, 0, 10],
'order_date': pd.to_datetime([
'2024-01-05','2024-01-12','2024-01-20','2024-02-03',
'2024-02-14','2024-02-28','2024-03-07','2024-03-15',
'2024-03-22','2024-04-01','2024-04-10','2024-04-18',
'2024-05-02','2024-05-11','2024-05-20','2024-06-03',
'2024-06-15','2024-07-01','2024-07-19','2024-08-05']),
'status': ['Delivered','Delivered','Pending','Delivered','Cancelled',
'Delivered','Delivered','Pending','Delivered','Delivered',
'Cancelled','Delivered','Delivered','Pending','Delivered',
'Delivered','Cancelled','Delivered','Delivered','Pending'],
'rating': [4.5, 3.8, None, 4.9, None, 4.0, 4.2, None, 3.5, 4.7,
None, 4.1, 4.8, None, 4.3, 3.9, None, 4.6, 4.0, None]
}
df = pd.DataFrame(data)
# Helpful derived column (you can add this yourself in Q14)
# df['total_price'] = df['quantity'] * df['price']
df

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,NaN
5,1006,Sara,Karachi,Books,Novel,1,800,0,2024-02-28,Delivered,4.0
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.2
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN
8,1009,Zara,Karachi,Books,Notebook,5,300,5,2024-03-22,Delivered,3.5
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN
11,1012,Ahmed,Karachi,Books,Cook Book,3,900,10,2024-04-18,Delivered,4.1
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3
15,1016,Zara,Karachi,Books,Textbook,2,1200,0,2024-06-03,Delivered,3.9
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,NaN
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.6
18,1019,Mia,Lahore,Books,Dictionary,2,700,0,2024-07-19,Delivered,4.0
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN

In [ ]:
# Q1. Load the dataset and display the first 7 rows. Also check how many rows and columns are
# there in total.
df.head(7)
df.shape

(   order_id customer_name       city     category      product  quantity  \
 0      1001           Ali     Lahore  Electronics       Laptop         1
 1      1002          Sara    Karachi     Clothing      T-Shirt         3
 2      1003          John  Islamabad        Books  Python Book         2
 3      1004           Mia     Lahore  Electronics   Headphones         1
 4      1005         Ahmed    Karachi     Clothing        Jeans         2
 5      1006          Sara    Karachi        Books        Novel         1
 6      1007          John  Islamabad  Electronics      Charger         4

    price  discount_pct order_date     status  rating
 0  75000            10 2024-01-05  Delivered     4.5
 1   1200             0 2024-01-12  Delivered     3.8
 2   1800             5 2024-01-20    Pending     NaN
 3   4500            15 2024-02-03  Delivered     4.9
 4   2500             0 2024-02-14  Cancelled     NaN
 5    800             0 2024-02-28  Delivered     4.0
 6    600            20 2024-03-07  Delivered     4.2  ,
 (20, 11))

In [13]:
# Q2. Show the name of every column in the dataset and the data type of each column.
df.columns
df.dtypes

order_id                  int64
customer_name               str
city                        str
category                    str
product                     str
quantity                  int64
price                     int64
discount_pct              int64
order_date       datetime64[us]
status                      str
rating                  float64
dtype: object

In [4]:
# Q3. Select only the 'customer_name', 'product', and 'price' columns and display them.
df[["customer_name","product","price"]]

   customer_name      product  price
0            Ali       Laptop  75000
1           Sara      T-Shirt   1200
2           John  Python Book   1800
3            Mia   Headphones   4500
4          Ahmed        Jeans   2500
5           Sara        Novel    800
6           John      Charger    600
7            Ali       Hoodie   2200
8           Zara     Notebook    300
9           Omar       Tablet  45000
10           Mia        Dress   1500
11         Ahmed    Cook Book    900
12          Sara   Smartwatch  12000
13          John       Jacket   3500
14           Ali        Mouse   1100
15          Zara     Textbook   1200
16          Omar        Scarf    800
17         Ahmed      Earbuds   3200
18           Mia   Dictionary    700
19           Ali       Gloves   1400

In [8]:
# Q4. Filter the data to show only the orders where the city is 'Lahore'.
df[df["city"] == "Lahore"]

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3
18,1019,Mia,Lahore,Books,Dictionary,2,700,0,2024-07-19,Delivered,4.0
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN

In [ ]:
# Q5. Find how many orders are there for each city. Which city placed the most orders?
df["city"].value_counts()
print(f"The City which placed the most orders is:  {df["city"].value_counts().head(1).index[0]}")

The City which placed the most orders is Karachi

In [18]:
# Q6. Show all orders where the price is more than 5000.
df[df["price"] > 5000]

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8

In [ ]:
# Q7. How many missing (NaN) values are there in each column? Which column has the most
# missing values?
df.isnull().sum() # ---> first part

order_id         0
customer_name    0
city             0
category         0
product          0
quantity         0
price            0
discount_pct     0
order_date       0
status           0
rating           7
dtype: int64

In [27]:
col = df.isnull().sum().sort_values(ascending= False).head(1).index[0]
print(f"The Column which hs most NaN values is: \"{col}\"")

The Column which hs most NaN values is: "rating"

In [30]:
# Q8. Sort the entire table by price from highest to lowest and show the top 5 rows.
df.sort_values("price",ascending=False).head(5)

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN

In [37]:
# Q9. What is the average price of all products? Also find the minimum and maximum price.
avg = df["price"].mean()
min = df["price"].min()
max = df["price"].max()
print(f"The Average price is: {avg}, min Price is: {min} and max Price is: {max}")

The Average price is: 8010.0, min Price is: 300 and max Price is: 75000

In [41]:
# Q10. Rename the column 'discount_pct' to 'discount_%' and then rename it back. This teaches you
# how to rename columns safely
df.rename(columns= {"discount_pct": "discount_%"}).rename(columns={"discount_%": "discount_pct"})

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,NaN
5,1006,Sara,Karachi,Books,Novel,1,800,0,2024-02-28,Delivered,4.0
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.2
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN
8,1009,Zara,Karachi,Books,Notebook,5,300,5,2024-03-22,Delivered,3.5
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN
11,1012,Ahmed,Karachi,Books,Cook Book,3,900,10,2024-04-18,Delivered,4.1
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3
15,1016,Zara,Karachi,Books,Textbook,2,1200,0,2024-06-03,Delivered,3.9
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,NaN
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.6
18,1019,Mia,Lahore,Books,Dictionary,2,700,0,2024-07-19,Delivered,4.0
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN