# **Questions 11 - 20**   **(Medium)**

In [1]:
import numpy as np
import pandas as pd

In [3]:
# Dataset
data = {
'order_id': [1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,
1011,1012,1013,1014,1015,1016,1017,1018,1019,1020],
'customer_name':['Ali','Sara','John','Mia','Ahmed','Sara','John','Ali',
'Zara','Omar','Mia','Ahmed','Sara','John','Ali','Zara',
'Omar','Ahmed','Mia','Ali'],
'city': ['Lahore','Karachi','Islamabad','Lahore','Karachi',
'Karachi','Islamabad','Lahore','Karachi','Islamabad',
'Lahore','Karachi','Karachi','Islamabad','Lahore',
'Karachi','Islamabad','Karachi','Lahore','Lahore'],
'category': ['Electronics','Clothing','Books','Electronics','Clothing',
'Books','Electronics','Clothing','Books','Electronics',
'Clothing','Books','Electronics','Clothing','Electronics',
'Books','Clothing','Electronics','Books','Clothing'],
'product': ['Laptop','T-Shirt','Python Book','Headphones','Jeans',
'Novel','Charger','Hoodie','Notebook','Tablet',
'Dress','Cook Book','Smartwatch','Jacket','Mouse',
'Textbook','Scarf','Earbuds','Dictionary','Gloves'],
'quantity': [1, 3, 2, 1, 2, 1, 4, 2, 5, 1,
2, 3, 1, 2, 3, 2, 4, 1, 2, 3],
'price': [75000, 1200, 1800, 4500, 2500,
800, 600, 2200, 300, 45000,
1500, 900, 12000,3500, 1100,
1200, 800, 3200, 700, 1400],
'discount_pct': [10, 0, 5, 15, 0, 0, 20, 10, 5, 5,
0, 10, 15, 0, 10, 0, 5, 20, 0, 10],
'order_date': pd.to_datetime([
'2024-01-05','2024-01-12','2024-01-20','2024-02-03',
'2024-02-14','2024-02-28','2024-03-07','2024-03-15',
'2024-03-22','2024-04-01','2024-04-10','2024-04-18',
'2024-05-02','2024-05-11','2024-05-20','2024-06-03',
'2024-06-15','2024-07-01','2024-07-19','2024-08-05']),
'status': ['Delivered','Delivered','Pending','Delivered','Cancelled',
'Delivered','Delivered','Pending','Delivered','Delivered',
'Cancelled','Delivered','Delivered','Pending','Delivered',
'Delivered','Cancelled','Delivered','Delivered','Pending'],
'rating': [4.5, 3.8, None, 4.9, None, 4.0, 4.2, None, 3.5, 4.7,
None, 4.1, 4.8, None, 4.3, 3.9, None, 4.6, 4.0, None]
}
df = pd.DataFrame(data)
# Helpful derived column (you can add this yourself in Q14)
# df['total_price'] = df['quantity'] * df['price']
df.head(3)

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN

In [ ]:
# Q11. Find the total revenue for each category (Electronics, Clothing, Books). Total revenue =
# quantity × price. Which category earns the most?

# My logic
def revenue(group):
    group["revenue"] = group["quantity"] * group["price"]
    return  group["revenue"].sum()


df.groupby("category").apply(revenue).sort_values(ascending=False) # part 01

category
Electronics    145400
Clothing        30400
Books           12400
dtype: int64

In [ ]:
catg = df.groupby("category").apply(revenue).sort_values(ascending=False).head(1).index[0] # part 2
print(f"The Category which earns the most is: {catg}")

The Category which earns the most is: Electronics

In [ ]:
# Actual method:
df["revenue"] = df["quantity"] * df["price"]
df.groupby("category")["revenue"].sum().sort_values(ascending = False) # 1st part

category
Electronics    145400
Clothing        30400
Books           12400
Name: revenue, dtype: int64

In [ ]:
catg1 = df.groupby("category")["revenue"].sum().sort_values(ascending = False).head(1).index[0] # part 2
print(f"The Category which earns the most is: {catg1}")

The Category which earns the most is: Electronics

In [30]:
# Q12. Show only the orders that have a discount greater than 0 AND belong to the 'Electronics'
# category.
# 1st method
df[(df["discount_pct"] > 0) & (df["category"] == "Electronics")]

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,revenue
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5,75000
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9,4500
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.2,2400
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7,45000
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8,12000
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3,3300
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.6,3200

In [38]:
# 2nd method
electronics = df.groupby("category").get_group("Electronics")
electronics[electronics["discount_pct"] >0]

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,revenue
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5,75000
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9,4500
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.2,2400
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7,45000
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8,12000
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3,3300
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.6,3200

In [49]:
# Q13. Fill the missing values in the 'rating' column with the average rating. Do this on a copy of the
# DataFrame so the original is unchanged.
df_copy = df.copy()


df_copy["rating"] = df_copy["rating"].fillna(np.round(df_copy["rating"].mean(),2))
df_copy

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,revenue
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.50,75000
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.80,3600
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,4.25,3600
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.90,4500
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,4.25,5000
5,1006,Sara,Karachi,Books,Novel,1,800,0,2024-02-28,Delivered,4.00,800
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.20,2400
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,4.25,4400
8,1009,Zara,Karachi,Books,Notebook,5,300,5,2024-03-22,Delivered,3.50,1500
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.70,45000
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,4.25,3000
11,1012,Ahmed,Karachi,Books,Cook Book,3,900,10,2024-04-18,Delivered,4.10,2700
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.80,12000
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,4.25,7000
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.30,3300
15,1016,Zara,Karachi,Books,Textbook,2,1200,0,2024-06-03,Delivered,3.90,2400
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,4.25,3200
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.60,3200
18,1019,Mia,Lahore,Books,Dictionary,2,700,0,2024-07-19,Delivered,4.00,1400
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,4.25,4200

In [57]:
# Q14. Add a new column called 'final_price' which is the price after applying the discount. Formula:
# final_price = price × (1 - discount_pct / 100).
df["final_price"]= df["price"] * (1 - (df["discount_pct"]/100))
df.head(3)

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,revenue,final_price
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5,75000,67500.0
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8,3600,1200.0
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN,3600,1710.0

In [64]:
# Q15. Find the top 3 customers who spent the most money in total. (Use quantity × price as
# spending.)
df.sort_values("revenue",ascending= False)[["customer_name","revenue"]].rename(columns={"revenue": "spending"}).head(3)

   customer_name  spending
0            Ali     75000
9           Omar     45000
12          Sara     12000

In [12]:
# Q16. Extract the month number from 'order_date' into a new column called 'month'. Then count
# how many orders were placed each month.
df["month"] = df["order_date"].dt.month
df.groupby("month")["customer_name"].count()

month
1    3
2    3
3    3
4    3
5    3
6    2
7    2
8    1
Name: customer_name, dtype: int64

In [ ]:
# Q17. Show all orders where the status is either 'Cancelled' or 'Pending'.
df[(df["status"] == "Cancelled") | (df["status"] =="Pending")] # 1st method

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,month
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN,1
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,NaN,2
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN,3
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN,4
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN,5
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,NaN,6
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN,8

In [ ]:
df[df["status"].isin(["Cancelled","Pending"])] # using isin() --> 2nd method

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,month
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN,1
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,NaN,2
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN,3
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN,4
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN,5
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,NaN,6
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN,8

In [30]:
# Q18. Find the average rating for each product category, but ignore the missing ratings (NaN) when
# calculating.  
np.round(df.groupby("category")["rating"].mean(skipna=True),2) # skipna = True (Default)

category
Books          3.90
Clothing       3.80
Electronics    4.57
Name: rating, dtype: float64

In [ ]:
# Q19. Create a new column 'is_expensive' that is True if the price is above 5000, and False
# otherwise. Then count how many expensive vs non-expensive products there are.
df["is_expensive"] = df["price"] > 5000
df.groupby("is_expensive")["customer_name"].count().reset_index()  # 1st method

   is_expensive  customer_name
0         False             17
1          True              3

In [ ]:
df["is_expensive"].value_counts().reset_index() # 2nd method

   is_expensive  count
0         False     17
1          True      3

In [51]:
# Q20. Show the customer name, product, and final_price for the 5 most expensive orders after
# discount. (You need the 'final_price' column from Q14.)
df["final_price"] = df["price"] * (1 - (df["discount_pct"]/100))
df.sort_values("final_price",ascending = False).head(5)[["customer_name","product","final_price"]]

   customer_name     product  final_price
0            Ali      Laptop      67500.0
9           Omar      Tablet      42750.0
12          Sara  Smartwatch      10200.0
3            Mia  Headphones       3825.0
13          John      Jacket       3500.0