## **Questions 21 - 28** **(Hard)**

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Dataset
data = {
'order_id': [1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,
1011,1012,1013,1014,1015,1016,1017,1018,1019,1020],
'customer_name':['Ali','Sara','John','Mia','Ahmed','Sara','John','Ali',
'Zara','Omar','Mia','Ahmed','Sara','John','Ali','Zara',
'Omar','Ahmed','Mia','Ali'],
'city': ['Lahore','Karachi','Islamabad','Lahore','Karachi',
'Karachi','Islamabad','Lahore','Karachi','Islamabad',
'Lahore','Karachi','Karachi','Islamabad','Lahore',
'Karachi','Islamabad','Karachi','Lahore','Lahore'],
'category': ['Electronics','Clothing','Books','Electronics','Clothing',
'Books','Electronics','Clothing','Books','Electronics',
'Clothing','Books','Electronics','Clothing','Electronics',
'Books','Clothing','Electronics','Books','Clothing'],
'product': ['Laptop','T-Shirt','Python Book','Headphones','Jeans',
'Novel','Charger','Hoodie','Notebook','Tablet',
'Dress','Cook Book','Smartwatch','Jacket','Mouse',
'Textbook','Scarf','Earbuds','Dictionary','Gloves'],
'quantity': [1, 3, 2, 1, 2, 1, 4, 2, 5, 1,
2, 3, 1, 2, 3, 2, 4, 1, 2, 3],
'price': [75000, 1200, 1800, 4500, 2500,
800, 600, 2200, 300, 45000,
1500, 900, 12000,3500, 1100,
1200, 800, 3200, 700, 1400],
'discount_pct': [10, 0, 5, 15, 0, 0, 20, 10, 5, 5,
0, 10, 15, 0, 10, 0, 5, 20, 0, 10],
'order_date': pd.to_datetime([
'2024-01-05','2024-01-12','2024-01-20','2024-02-03',
'2024-02-14','2024-02-28','2024-03-07','2024-03-15',
'2024-03-22','2024-04-01','2024-04-10','2024-04-18',
'2024-05-02','2024-05-11','2024-05-20','2024-06-03',
'2024-06-15','2024-07-01','2024-07-19','2024-08-05']),
'status': ['Delivered','Delivered','Pending','Delivered','Cancelled',
'Delivered','Delivered','Pending','Delivered','Delivered',
'Cancelled','Delivered','Delivered','Pending','Delivered',
'Delivered','Cancelled','Delivered','Delivered','Pending'],
'rating': [4.5, 3.8, None, 4.9, None, 4.0, 4.2, None, 3.5, 4.7,
None, 4.1, 4.8, None, 4.3, 3.9, None, 4.6, 4.0, None]
}
df = pd.DataFrame(data)
# Helpful derived column (you can add this yourself in Q14)
# df['total_price'] = df['quantity'] * df['price']
df

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,NaN
5,1006,Sara,Karachi,Books,Novel,1,800,0,2024-02-28,Delivered,4.0
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.2
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN
8,1009,Zara,Karachi,Books,Notebook,5,300,5,2024-03-22,Delivered,3.5
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN
11,1012,Ahmed,Karachi,Books,Cook Book,3,900,10,2024-04-18,Delivered,4.1
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3
15,1016,Zara,Karachi,Books,Textbook,2,1200,0,2024-06-03,Delivered,3.9
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,NaN
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.6
18,1019,Mia,Lahore,Books,Dictionary,2,700,0,2024-07-19,Delivered,4.0
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN

In [10]:
# Q21. Find how many unique customers placed orders in each city. For example, Lahore had X
# distinct customers.
df.groupby("city")["customer_name"].nunique()

city
Islamabad    2
Karachi      3
Lahore       2
Name: customer_name, dtype: int64

In [22]:
# Q22. Find the most popular product (highest total quantity sold) in each category.
df.groupby(["category","product"])["quantity"].sum().sort_values(ascending=False).head(3) # 1st method

category     product
Books        Notebook    5
Clothing     Scarf       4
Electronics  Charger     4
Name: quantity, dtype: int64

In [ ]:
# df.groupby(["category","product"])["quantity"].sum().idxmax() # ---> 2nd method
# but idxmax gives only the index labels of that group which has max value (it is not giving max for each group)

category     product
Books        Cook Book      3
             Dictionary     2
             Notebook       5
             Novel          1
             Python Book    2
             Textbook       2
Clothing     Dress          2
             Gloves         3
             Hoodie         2
             Jacket         2
             Jeans          2
             Scarf          4
             T-Shirt        3
Electronics  Charger        4
             Earbuds        1
             Headphones     1
             Laptop         1
             Mouse          3
             Smartwatch     1
             Tablet         1
Name: quantity, dtype: int64

In [3]:
# Q23. Create a pivot table that shows the total revenue (quantity × price) for each city (rows) and
# each category (columns).
df["revenue"] = df["quantity"] * df["price"]
df.pivot_table(index=["city"],columns=["category"],values= ["revenue"])

          revenue
category    Books     Clothing Electronics
city
Islamabad  3600.0  5100.000000     23700.0
Karachi    1850.0  4300.000000      7600.0
Lahore     1400.0  3866.666667     27600.0

In [15]:
# Q24. Find all customers who ordered more than once (appear more than once in the data). Show
# only their names and how many times they ordered.
df["customer_name"].value_counts()# 1st method

customer_name
Ali      4
Sara     3
John     3
Mia      3
Ahmed    3
Zara     2
Omar     2
Name: count, dtype: int64

In [10]:
# 2nd method
df.groupby("customer_name")["customer_name"].count().sort_values(ascending = False)

customer_name
Ali      4
Ahmed    3
John     3
Mia      3
Sara     3
Omar     2
Zara     2
Name: customer_name, dtype: int64

In [8]:
# Q25. Calculate the month-over-month total revenue. Which month had the highest revenue?
df["month"] = df["order_date"].dt.month_name()
month_rev= df.groupby("month")["revenue"].sum().sort_values(ascending = False).head(1).index[0]
print(f"The month which has the highest revenue is : {month_rev}")

The month which has the highest revenue is : January

In [ ]:
# Q26. For each customer, find their average discount percentage. Then show only customers who
# received an average discount above 10%.
avg_dct = np.round(df.groupby("customer_name")["discount_pct"].mean(),2)
avg_dct[avg_dct >10] # answer is empty series not a single customer get avg, discount >10%
pd.cut()

Series([], Name: discount_pct, dtype: float64)

In [ ]:
# Q27. Mark orders as 'High Value' if revenue (quantity × price) is above 10,000, 'Medium Value' if
# between 3,000 and 10,000, and 'Low Value' if below 3,000. Add this as a new column called
# 'order_value_tier'.

def order_tier(revenue):
    if revenue > 10000:
        return "High Value"
    elif (revenue >= 3000) & (revenue <10000):
        return "Medium Value"
    elif revenue < 3000:
        return "Low Value"
    

df["order_value_tier"] = df["revenue"].apply(order_tier)
df

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,revenue,order_value_tier
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5,75000,High Value
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8,3600,Medium Value
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN,3600,Medium Value
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9,4500,Medium Value
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,NaN,5000,Medium Value
5,1006,Sara,Karachi,Books,Novel,1,800,0,2024-02-28,Delivered,4.0,800,Low Value
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.2,2400,Low Value
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN,4400,Medium Value
8,1009,Zara,Karachi,Books,Notebook,5,300,5,2024-03-22,Delivered,3.5,1500,Low Value
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7,45000,High Value
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN,3000,Medium Value
11,1012,Ahmed,Karachi,Books,Cook Book,3,900,10,2024-04-18,Delivered,4.1,2700,Low Value
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8,12000,High Value
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN,7000,Medium Value
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3,3300,Medium Value
15,1016,Zara,Karachi,Books,Textbook,2,1200,0,2024-06-03,Delivered,3.9,2400,Low Value
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,NaN,3200,Medium Value
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.6,3200,Medium Value
18,1019,Mia,Lahore,Books,Dictionary,2,700,0,2024-07-19,Delivered,4.0,1400,Low Value
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN,4200,Medium Value

In [36]:
# Q28. Find the percentage share of each category's revenue out of the total revenue. Round to 2
# decimal places.
tot_reven = df["revenue"].sum()
group_reven = df.groupby("category")["revenue"].sum() 
np.round((group_reven/tot_reven) * 100,2).reset_index().rename(columns={"revenue":"revenue_%"})

      category  revenue_%
0        Books       6.59
1     Clothing      16.15
2  Electronics      77.26