## **Questions 29 - 35** **(Advanced)**

In [2]:
import numpy as np 
import pandas as pd

In [5]:
# Dataset
data = {
'order_id': [1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,
1011,1012,1013,1014,1015,1016,1017,1018,1019,1020],
'customer_name':['Ali','Sara','John','Mia','Ahmed','Sara','John','Ali',
'Zara','Omar','Mia','Ahmed','Sara','John','Ali','Zara',
'Omar','Ahmed','Mia','Ali'],
'city': ['Lahore','Karachi','Islamabad','Lahore','Karachi',
'Karachi','Islamabad','Lahore','Karachi','Islamabad',
'Lahore','Karachi','Karachi','Islamabad','Lahore',
'Karachi','Islamabad','Karachi','Lahore','Lahore'],
'category': ['Electronics','Clothing','Books','Electronics','Clothing',
'Books','Electronics','Clothing','Books','Electronics',
'Clothing','Books','Electronics','Clothing','Electronics',
'Books','Clothing','Electronics','Books','Clothing'],
'product': ['Laptop','T-Shirt','Python Book','Headphones','Jeans',
'Novel','Charger','Hoodie','Notebook','Tablet',
'Dress','Cook Book','Smartwatch','Jacket','Mouse',
'Textbook','Scarf','Earbuds','Dictionary','Gloves'],
'quantity': [1, 3, 2, 1, 2, 1, 4, 2, 5, 1,
2, 3, 1, 2, 3, 2, 4, 1, 2, 3],
'price': [75000, 1200, 1800, 4500, 2500,
800, 600, 2200, 300, 45000,
1500, 900, 12000,3500, 1100,
1200, 800, 3200, 700, 1400],
'discount_pct': [10, 0, 5, 15, 0, 0, 20, 10, 5, 5,
0, 10, 15, 0, 10, 0, 5, 20, 0, 10],
'order_date': pd.to_datetime([
'2024-01-05','2024-01-12','2024-01-20','2024-02-03',
'2024-02-14','2024-02-28','2024-03-07','2024-03-15',
'2024-03-22','2024-04-01','2024-04-10','2024-04-18',
'2024-05-02','2024-05-11','2024-05-20','2024-06-03',
'2024-06-15','2024-07-01','2024-07-19','2024-08-05']),
'status': ['Delivered','Delivered','Pending','Delivered','Cancelled',
'Delivered','Delivered','Pending','Delivered','Delivered',
'Cancelled','Delivered','Delivered','Pending','Delivered',
'Delivered','Cancelled','Delivered','Delivered','Pending'],
'rating': [4.5, 3.8, None, 4.9, None, 4.0, 4.2, None, 3.5, 4.7,
None, 4.1, 4.8, None, 4.3, 3.9, None, 4.6, 4.0, None]
}
df = pd.DataFrame(data)
# Helpful derived column (you can add this yourself in Q14)
# df['total_price'] = df['quantity'] * df['price']
df

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,NaN
5,1006,Sara,Karachi,Books,Novel,1,800,0,2024-02-28,Delivered,4.0
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.2
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN
8,1009,Zara,Karachi,Books,Notebook,5,300,5,2024-03-22,Delivered,3.5
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN
11,1012,Ahmed,Karachi,Books,Cook Book,3,900,10,2024-04-18,Delivered,4.1
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3
15,1016,Zara,Karachi,Books,Textbook,2,1200,0,2024-06-03,Delivered,3.9
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,NaN
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.6
18,1019,Mia,Lahore,Books,Dictionary,2,700,0,2024-07-19,Delivered,4.0
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN

In [7]:
# Q29. Rank customers by their total spending (quantity × price). Add a column 'spending_rank'
# where rank 1 = highest spender. Customers with equal spending should share the same rank.
df["total_spending"] = df["quantity"] * df["price"]
df["spending_rank"] = df["total_spending"].rank(method= "min", ascending = False)
df.sort_values("spending_rank")

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,total_spending,spending_rank
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5,75000,1.0
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7,45000,2.0
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8,12000,3.0
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN,7000,4.0
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,NaN,5000,5.0
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9,4500,6.0
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN,4400,7.0
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN,4200,8.0
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8,3600,9.0
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN,3600,9.0
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3,3300,11.0
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,NaN,3200,12.0
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.6,3200,12.0
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN,3000,14.0
11,1012,Ahmed,Karachi,Books,Cook Book,3,900,10,2024-04-18,Delivered,4.1,2700,15.0
15,1016,Zara,Karachi,Books,Textbook,2,1200,0,2024-06-03,Delivered,3.9,2400,16.0
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.2,2400,16.0
8,1009,Zara,Karachi,Books,Notebook,5,300,5,2024-03-22,Delivered,3.5,1500,18.0
18,1019,Mia,Lahore,Books,Dictionary,2,700,0,2024-07-19,Delivered,4.0,1400,19.0
5,1006,Sara,Karachi,Books,Novel,1,800,0,2024-02-28,Delivered,4.0,800,20.0

In [18]:
df.head(3)

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,total_spending,spending_rank
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5,75000,1.0
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8,3600,9.0
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN,3600,9.0

In [8]:
# Q30. For each order, calculate the cumulative revenue over time (sorted by order_date). Add this
# as a column 'cumulative_revenue'
df["cumulative_revenue"] = np.cumsum(df["total_spending"])
df

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,total_spending,spending_rank,cumulative_revenue
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5,75000,1.0,75000
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8,3600,9.0,78600
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN,3600,9.0,82200
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9,4500,6.0,86700
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,NaN,5000,5.0,91700
5,1006,Sara,Karachi,Books,Novel,1,800,0,2024-02-28,Delivered,4.0,800,20.0,92500
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.2,2400,16.0,94900
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN,4400,7.0,99300
8,1009,Zara,Karachi,Books,Notebook,5,300,5,2024-03-22,Delivered,3.5,1500,18.0,100800
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7,45000,2.0,145800
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN,3000,14.0,148800
11,1012,Ahmed,Karachi,Books,Cook Book,3,900,10,2024-04-18,Delivered,4.1,2700,15.0,151500
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8,12000,3.0,163500
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN,7000,4.0,170500
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3,3300,11.0,173800
15,1016,Zara,Karachi,Books,Textbook,2,1200,0,2024-06-03,Delivered,3.9,2400,16.0,176200
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,NaN,3200,12.0,179400
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.6,3200,12.0,182600
18,1019,Mia,Lahore,Books,Dictionary,2,700,0,2024-07-19,Delivered,4.0,1400,19.0,184000
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN,4200,8.0,188200

In [9]:
# Q31. Find which city has the highest cancellation rate (cancelled orders ÷ total orders × 100)
total_orders = df.shape[0]
cancelled_df = df[df["status"] =="Cancelled"]
cancelled_order = cancelled_df.groupby("city")["status"].count()

cancelled_per = (cancelled_order/total_orders) * 100
cancelled_per # each city has 1 cancelled order and rate is 5% so all these are has highest cancellation rate

city
Islamabad    5.0
Karachi      5.0
Lahore       5.0
Name: status, dtype: float64

In [10]:
# Q32. Use .apply() to create a custom function that gives a 'performance label' to each order: if
# rating >= 4.5 → 'Excellent', 3.5–4.4 → 'Good', below 3.5 → 'Needs Improvement', NaN → 'Not
# Rated'.

def performance(rating):
    if rating  >=4.5:
        return "Excellent"
    elif (rating >=3.5) & (rating <=4.4):
        return "Needs Improvement"
    elif (rating == np.nan) | (rating == None):
        return "Not Rated"


df["performance_label"] = df["rating"].apply(performance)
df

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,total_spending,spending_rank,cumulative_revenue,performance_label
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5,75000,1.0,75000,Excellent
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8,3600,9.0,78600,Needs Improvement
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN,3600,9.0,82200,NaN
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9,4500,6.0,86700,Excellent
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,NaN,5000,5.0,91700,NaN
5,1006,Sara,Karachi,Books,Novel,1,800,0,2024-02-28,Delivered,4.0,800,20.0,92500,Needs Improvement
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.2,2400,16.0,94900,Needs Improvement
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN,4400,7.0,99300,NaN
8,1009,Zara,Karachi,Books,Notebook,5,300,5,2024-03-22,Delivered,3.5,1500,18.0,100800,Needs Improvement
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7,45000,2.0,145800,Excellent
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN,3000,14.0,148800,NaN
11,1012,Ahmed,Karachi,Books,Cook Book,3,900,10,2024-04-18,Delivered,4.1,2700,15.0,151500,Needs Improvement
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8,12000,3.0,163500,Excellent
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN,7000,4.0,170500,NaN
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3,3300,11.0,173800,Needs Improvement
15,1016,Zara,Karachi,Books,Textbook,2,1200,0,2024-06-03,Delivered,3.9,2400,16.0,176200,Needs Improvement
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,NaN,3200,12.0,179400,NaN
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.6,3200,12.0,182600,Excellent
18,1019,Mia,Lahore,Books,Dictionary,2,700,0,2024-07-19,Delivered,4.0,1400,19.0,184000,Needs Improvement
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN,4200,8.0,188200,NaN

In [14]:
# Q33. Reshape the data: create a wide-format table where each row is a customer, each column is
# a product category, and the values are the total amount spent by that customer in that category.
# Fill missing combinations with 0.

# 1st method using pivot_table()
df.pivot_table(index="customer_name",columns="category",values="total_spending").fillna(0)

category        Books  Clothing  Electronics
customer_name
Ahmed          2700.0    5000.0       3200.0
Ali               0.0    4300.0      39150.0
John           3600.0    7000.0       2400.0
Mia            1400.0    3000.0       4500.0
Omar              0.0    3200.0      45000.0
Sara            800.0    3600.0      12000.0
Zara           1950.0       0.0          0.0

In [ ]:
# 2nd method ---> by using groupby,unstack() and set_index
df.set_index(["customer_name","category"]).groupby(["customer_name","category"])["total_spending"].sum().unstack().fillna(0)

category        Books  Clothing  Electronics
customer_name
Ahmed          2700.0    5000.0       3200.0
Ali               0.0    8600.0      78300.0
John           3600.0    7000.0       2400.0
Mia            1400.0    3000.0       4500.0
Omar              0.0    3200.0      45000.0
Sara            800.0    3600.0      12000.0
Zara           3900.0       0.0          0.0

In [31]:
df

,order_id,customer_name,city,category,product,quantity,price,discount_pct,order_date,status,rating,total_spending,spending_rank,cumulative_revenue,performance_label
0,1001,Ali,Lahore,Electronics,Laptop,1,75000,10,2024-01-05,Delivered,4.5,75000,1.0,75000,Excellent
1,1002,Sara,Karachi,Clothing,T-Shirt,3,1200,0,2024-01-12,Delivered,3.8,3600,9.0,78600,Needs Improvement
2,1003,John,Islamabad,Books,Python Book,2,1800,5,2024-01-20,Pending,NaN,3600,9.0,82200,NaN
3,1004,Mia,Lahore,Electronics,Headphones,1,4500,15,2024-02-03,Delivered,4.9,4500,6.0,86700,Excellent
4,1005,Ahmed,Karachi,Clothing,Jeans,2,2500,0,2024-02-14,Cancelled,NaN,5000,5.0,91700,NaN
5,1006,Sara,Karachi,Books,Novel,1,800,0,2024-02-28,Delivered,4.0,800,20.0,92500,Needs Improvement
6,1007,John,Islamabad,Electronics,Charger,4,600,20,2024-03-07,Delivered,4.2,2400,16.0,94900,Needs Improvement
7,1008,Ali,Lahore,Clothing,Hoodie,2,2200,10,2024-03-15,Pending,NaN,4400,7.0,99300,NaN
8,1009,Zara,Karachi,Books,Notebook,5,300,5,2024-03-22,Delivered,3.5,1500,18.0,100800,Needs Improvement
9,1010,Omar,Islamabad,Electronics,Tablet,1,45000,5,2024-04-01,Delivered,4.7,45000,2.0,145800,Excellent
10,1011,Mia,Lahore,Clothing,Dress,2,1500,0,2024-04-10,Cancelled,NaN,3000,14.0,148800,NaN
11,1012,Ahmed,Karachi,Books,Cook Book,3,900,10,2024-04-18,Delivered,4.1,2700,15.0,151500,Needs Improvement
12,1013,Sara,Karachi,Electronics,Smartwatch,1,12000,15,2024-05-02,Delivered,4.8,12000,3.0,163500,Excellent
13,1014,John,Islamabad,Clothing,Jacket,2,3500,0,2024-05-11,Pending,NaN,7000,4.0,170500,NaN
14,1015,Ali,Lahore,Electronics,Mouse,3,1100,10,2024-05-20,Delivered,4.3,3300,11.0,173800,Needs Improvement
15,1016,Zara,Karachi,Books,Textbook,2,1200,0,2024-06-03,Delivered,3.9,2400,16.0,176200,Needs Improvement
16,1017,Omar,Islamabad,Clothing,Scarf,4,800,5,2024-06-15,Cancelled,NaN,3200,12.0,179400,NaN
17,1018,Ahmed,Karachi,Electronics,Earbuds,1,3200,20,2024-07-01,Delivered,4.6,3200,12.0,182600,Excellent
18,1019,Mia,Lahore,Books,Dictionary,2,700,0,2024-07-19,Delivered,4.0,1400,19.0,184000,Needs Improvement
19,1020,Ali,Lahore,Clothing,Gloves,3,1400,10,2024-08-05,Pending,NaN,4200,8.0,188200,NaN

In [ ]:
# Q34. For each customer, find the time gap (in days) between their first and last order. Show the
# result sorted from the customer with the longest gap to the shortest.


# in this question timedelta concept is used that i didn't cover yet.

first_order_date = df.groupby("customer_name")["order_date"].min()
last_order_date = df.groupby("customer_name")["order_date"].max()
(last_order_date - first_order_date).reset_index().rename(columns= {"order_date":"time_gap"}).sort_values("time_gap",ascending = False)

  customer_name time_gap
1           Ali 213 days
3           Mia 167 days
0         Ahmed 138 days
2          John 112 days
5          Sara 111 days
4          Omar  75 days
6          Zara  73 days

In [57]:
# in one line
((df.groupby("customer_name")["order_date"].max()) - (df.groupby("customer_name")["order_date"].min())).reset_index().rename(columns={"order_date": "time_gap"}).sort_values("time_gap",ascending = False)

  customer_name time_gap
1           Ali 213 days
3           Mia 167 days
0         Ahmed 138 days
2          John 112 days
5          Sara 111 days
4          Omar  75 days
6          Zara  73 days

In [ ]:
# Q35. Build a full summary report in one chained pipeline (no intermediate variables). The output
# should show: city, total orders, total revenue, avg rating (rounded to 2), and cancellation rate (%)
# — all in one DataFrame, sorted by total revenue descending

# Chained Pipeline

df.groupby("city")[["quantity","total_spending","rating",]].agg(func= {"quantity":"count","total_spending":"sum","rating":"mean",}).rename(columns = {"total_spending":"total_revenue","quantity":"total_orders","rating":"avg_rating"}).reset_index().merge(((df[df["status"] =="Cancelled"].groupby("city")["quantity"].count()/df.shape[0]) * 100).reset_index().rename(columns={"quantity":"cancellation_rate_%"})).sort_values("total_revenue",ascending = False)

        city  total_orders  total_revenue  avg_rating  cancellation_rate_%
2     Lahore             7          95800       4.425                  5.0
0  Islamabad             5          61200       4.450                  5.0
1    Karachi             8          31200       4.100                  5.0