# **EDA 02**

In [2]:
import numpy as np
import pandas as pd

In [3]:
# ---------- Dataset 1: messy retail orders (main dataset for Sections A & B) ----------
n = 500
df = pd.DataFrame(
  {
"order_id": range(1001, 1001 + n),
"customer_name": np.random.choice(
["Ali Khan", "sara ahmed", "JOHN SMITH", "Fatima Noor", np.nan, "Ali Khan "], n),
"order_date": pd.date_range("2024-01-01", periods=n, freq="6h").astype(str),
"category": np.random.choice(
["Electronics", "Clothing", "Grocery", "Toys", None], n, p=[0.3, 0.25, 0.25, 0.15, 0.05]),
"quantity": np.random.randint(1, 10, n).astype(float),
"unit_price": np.round(np.random.uniform(5, 500, n), 2),
"region": np.random.choice(["North", "South", "East", "West"], n),
"payment_method": np.random.choice(["Card", "Cash", "Card", "Online", None], n),
}
)
df = pd.concat([df, df.sample(15, random_state=1)], ignore_index=True) # inject duplicates
df.loc[df.sample(20, random_state=2).index, "quantity"] = np.nan # inject missing values
df.loc[df.sample(15, random_state=3).index, "unit_price"] = np.nan

In [4]:
df

,order_id,customer_name,order_date,category,quantity,unit_price,region,payment_method
0,1001,Fatima Noor,2024-01-01 00:00:00,Clothing,9.0,382.17,West,Card
1,1002,sara ahmed,2024-01-01 06:00:00,Clothing,NaN,464.58,South,Cash
2,1003,nan,2024-01-01 12:00:00,Toys,1.0,436.63,West,Cash
3,1004,Ali Khan,2024-01-01 18:00:00,Clothing,6.0,479.06,South,Card
4,1005,Fatima Noor,2024-01-02 00:00:00,Clothing,5.0,485.42,East,Card
...,...,...,...,...,...,...,...,...
510,1323,JOHN SMITH,2024-03-21 12:00:00,Grocery,5.0,424.28,South,Cash
511,1169,nan,2024-02-12 00:00:00,NaN,7.0,47.65,South,Card
512,1120,JOHN SMITH,2024-01-30 18:00:00,Electronics,1.0,492.92,South,Online
513,1067,JOHN SMITH,2024-01-17 12:00:00,Clothing,4.0,262.69,North,Cash
514,1306,Ali Khan,2024-03-17 06:00:00,Grocery,8.0,101.01,South,Card

In [13]:
# Q12. Drop missing rows
# Create a cleaned copy of df with all rows that have a missing customer_name removed.
df = df[df["customer_name"] != "nan"]
df

,order_id,customer_name,order_date,category,quantity,unit_price,region,payment_method
0,1001,Fatima Noor,2024-01-01 00:00:00,Clothing,9.0,382.17,West,Card
1,1002,sara ahmed,2024-01-01 06:00:00,Clothing,5.0,464.58,South,Cash
3,1004,Ali Khan,2024-01-01 18:00:00,Clothing,6.0,479.06,South,Card
4,1005,Fatima Noor,2024-01-02 00:00:00,Clothing,5.0,485.42,East,Card
5,1006,Ali Khan,2024-01-02 06:00:00,Clothing,6.0,82.17,South,NaN
...,...,...,...,...,...,...,...,...
509,1091,Fatima Noor,2024-01-23 12:00:00,Electronics,6.0,179.81,South,Cash
510,1323,JOHN SMITH,2024-03-21 12:00:00,Grocery,5.0,424.28,South,Cash
512,1120,JOHN SMITH,2024-01-30 18:00:00,Electronics,1.0,492.92,South,Online
513,1067,JOHN SMITH,2024-01-17 12:00:00,Clothing,4.0,262.69,North,Cash
514,1306,Ali Khan,2024-03-17 06:00:00,Grocery,8.0,101.01,South,Card

In [14]:
# Q13. Fill missing values
# Fill missing the values with the column's median.
median = df["quantity"].median()
df["quantity"] = df["quantity"].fillna(median)
df

,order_id,customer_name,order_date,category,quantity,unit_price,region,payment_method
0,1001,Fatima Noor,2024-01-01 00:00:00,Clothing,9.0,382.17,West,Card
1,1002,sara ahmed,2024-01-01 06:00:00,Clothing,5.0,464.58,South,Cash
3,1004,Ali Khan,2024-01-01 18:00:00,Clothing,6.0,479.06,South,Card
4,1005,Fatima Noor,2024-01-02 00:00:00,Clothing,5.0,485.42,East,Card
5,1006,Ali Khan,2024-01-02 06:00:00,Clothing,6.0,82.17,South,NaN
...,...,...,...,...,...,...,...,...
509,1091,Fatima Noor,2024-01-23 12:00:00,Electronics,6.0,179.81,South,Cash
510,1323,JOHN SMITH,2024-03-21 12:00:00,Grocery,5.0,424.28,South,Cash
512,1120,JOHN SMITH,2024-01-30 18:00:00,Electronics,1.0,492.92,South,Online
513,1067,JOHN SMITH,2024-01-17 12:00:00,Clothing,4.0,262.69,North,Cash
514,1306,Ali Khan,2024-03-17 06:00:00,Grocery,8.0,101.01,South,Card

In [15]:
# Q14. Create a derived column
# Add a new column total_amount equal to quantity * unit_price .

df["total_price"] = df["quantity"] * df["unit_price"]
df

,order_id,customer_name,order_date,category,quantity,unit_price,region,payment_method,total_price
0,1001,Fatima Noor,2024-01-01 00:00:00,Clothing,9.0,382.17,West,Card,3439.53
1,1002,sara ahmed,2024-01-01 06:00:00,Clothing,5.0,464.58,South,Cash,2322.90
3,1004,Ali Khan,2024-01-01 18:00:00,Clothing,6.0,479.06,South,Card,2874.36
4,1005,Fatima Noor,2024-01-02 00:00:00,Clothing,5.0,485.42,East,Card,2427.10
5,1006,Ali Khan,2024-01-02 06:00:00,Clothing,6.0,82.17,South,NaN,493.02
...,...,...,...,...,...,...,...,...,...
509,1091,Fatima Noor,2024-01-23 12:00:00,Electronics,6.0,179.81,South,Cash,1078.86
510,1323,JOHN SMITH,2024-03-21 12:00:00,Grocery,5.0,424.28,South,Cash,2121.40
512,1120,JOHN SMITH,2024-01-30 18:00:00,Electronics,1.0,492.92,South,Online,492.92
513,1067,JOHN SMITH,2024-01-17 12:00:00,Clothing,4.0,262.69,North,Cash,1050.76
514,1306,Ali Khan,2024-03-17 06:00:00,Grocery,8.0,101.01,South,Card,808.08

In [18]:
# Q15. A first groupby
# Compute total total_amount (from Q14) per region .

df.groupby("region")["total_price"].sum()

region
East     143580.06
North    143504.03
South    134261.48
West     106901.09
Name: total_price, dtype: float64

# SECTION B — INTERMEDIATE (Q16–Q35)
# Deeper wrangling, reshaping, merging, and exploratory analysis.